"""add appendix field to questions

Revision ID: 005f5cfcaf65
Revises: 20260307_add_question_images
Create Date: 2026-03-08 21:44:07.379569

"""
from alembic import op
import sqlalchemy as sa


revision = '005f5cfcaf65'
down_revision = '20260307_add_question_images'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_answer_images_question_id', table_name='answer_images')
    op.drop_index('uq_answer_images_order', table_name='answer_images')
    op.drop_constraint('answers_question_id_key', 'answers', type_='unique')
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=True)
    op.create_index(op.f('ix_api_call_logs_user_id'), 'api_call_logs', ['user_id'], unique=False)
    op.alter_column('exports', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('exports', 'format',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_index('ix_question_images_question_id', table_name='question_images')
    op.drop_index('uq_question_images_order', table_name='question_images')
    op.add_column('questions', sa.Column('appendix', sa.Text(), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('questions', 'appendix')
    op.create_index('uq_question_images_order', 'question_images', ['question_id', 'order_index'], unique=False)
    op.create_index('ix_question_images_question_id', 'question_images', ['question_id'], unique=False)
    op.alter_column('exports', 'format',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('exports', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_api_call_logs_user_id'), table_name='api_call_logs')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.create_unique_constraint('answers_question_id_key', 'answers', ['question_id'])
    op.create_index('uq_answer_images_order', 'answer_images', ['question_id', 'order_index'], unique=False)
    op.create_index('ix_answer_images_question_id', 'answer_images', ['question_id'], unique=False)
    # ### end Alembic commands ###
